openapi: 3.0.3
info:
  title: Swagger UnderExpo - OpenAPI 3.0
  description: Definição OpenAPI 3.0 para a API do projeto UnderExpo.
  termsOfService: http://swagger.io/terms/
  contact:
    email: gustavo.oliveira@aluno.riogrande.ifrs.edu.br
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: http://localhost:8080/api/v1
tags:
- name: exposicao
  description: Informações e operações relacionadas às exposições
- name: perfil
  description: Informações e operações relacionadas aos perfis de usuários
paths:
  /expo:
    get:
      tags:
      - exposicao
      summary: Buscar exposições publicadas com paginação
      description: "Busca exposições que tenham sido disponibilizadas ao público,\
        \ permitindo paginação."
      operationId: buscarExposicoesPublicadas
      parameters:
      - name: pagina
        in: query
        description: Página atual da busca
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          default: 0
      - name: quantidade
        in: query
        description: Quantidade de registros a serem buscados
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResumoExposicao'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResumoExposicao'
        "400":
          description: requisição inválida
      x-swagger-router-controller: Exposicao
    post:
      tags:
      - exposicao
      summary: Organizar uma nova exposição
      description: Adiciona uma nova exposição em modo rascunho
      operationId: organizarExposicao
      requestBody:
        description: Dados da nova exposição
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovaExposicao'
          application/xml:
            schema:
              $ref: '#/components/schemas/NovaExposicao'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NovaExposicao'
        required: true
      responses:
        "201":
          description: criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: dados invalidos
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Exposicao
  /expo/{expoId}:
    get:
      tags:
      - exposicao
      summary: Carregar uma exposição a partir do seu ID
      description: "Retorna uma única exposição, com uma lista de painéis."
      operationId: carregarExposicaoPorId
      parameters:
      - name: expoId
        in: path
        description: ID da exposição a ser carregada
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exposicao'
            application/xml:
              schema:
                $ref: '#/components/schemas/Exposicao'
        "400":
          description: id fornecido é inválido
        "404":
          description: exposição não encontrada
      x-swagger-router-controller: Exposicao
    put:
      tags:
      - exposicao
      summary: Alterar informações em uma exposição
      description: |-
        Atualiza as informações de uma exposição.
        Também irá alterar a ordem dos paineis que forem informados
      operationId: atualizarExposicao
      parameters:
      - name: expoId
        in: path
        description: ID da exposição cujas informações serão atualizadas
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Conteúdos que serão atualizados na exposição. Campos não informados
          não serão alterados.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AtualizacaoExposicao'
          application/xml:
            schema:
              $ref: '#/components/schemas/AtualizacaoExposicao'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AtualizacaoExposicao'
        required: true
      responses:
        "200":
          description: operacao bem sucedida
        "400":
          description: id fornecido é inválido
        "404":
          description: exposição não encontrada
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Exposicao
    delete:
      tags:
      - exposicao
      summary: Remover uma exposição
      description: |-
        Remove uma exposição e seus painéis.
        Pode ser feito apenas em exposições que não possuam painéis e estejam em modo rascunho.
      operationId: removerExposicao
      parameters:
      - name: expoId
        in: path
        description: ID da exposição cujas informações serão atualizadas
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: operacao bem sucedida
        "400":
          description: id fornecido é inválido
        "404":
          description: exposição não encontrada
        "409":
          description: não é possível excluir o recurso no momento
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Exposicao
  /expo/{expoId}/denuncia:
    post:
      tags:
      - exposicao
      summary: Denunciar uma exposição a partir do seu ID
      description: Cria uma denúncia associada a exposição com o ID informado
      operationId: denunciarExposicao
      parameters:
      - name: expoId
        in: path
        description: ID da exposição a ser denunciada
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Criar uma denúncia com uma descrição dos fatores ofensivos
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovaDenuncia'
          application/xml:
            schema:
              $ref: '#/components/schemas/NovaDenuncia'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NovaDenuncia'
        required: true
      responses:
        "200":
          description: operação bem sucedida
        "400":
          description: id fornecido é inválido
        "404":
          description: exposição não encontrada
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Exposicao
  /expo/{expoId}/miniatura:
    put:
      tags:
      - exposicao
      summary: Adicionar uma imagem de miniatura a uma exposição
      description: Carrega uma nova imagem como miniatura para a exposição
      operationId: adicionarMiniaturaExposicao
      parameters:
      - name: expoId
        in: path
        description: ID da exposição cuja miniatura será atualizada
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Imagem que será carregada como miniatura
        content:
          image/png:
            schema:
              type: string
              format: binary
          image/jpeg:
            schema:
              type: string
              format: binary
        required: true
      responses:
        "200":
          description: operacao bem sucedida
        "400":
          description: id fornecido é inválido
        "404":
          description: exposição não encontrada
        "413":
          description: conteúdo muito grande
        "415":
          description: tipo de mídia não suportado
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Exposicao
    delete:
      tags:
      - exposicao
      summary: Remover a imagem de miniatura de uma exposição
      description: "Remove a imagem de miniatura da exposição, caso possua"
      operationId: removerMiniaturaExposicao
      parameters:
      - name: expoId
        in: path
        description: ID da exposição cuja miniatura será removida
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: operacao bem sucedida
        "400":
          description: id fornecido é inválido
        "404":
          description: exposição não encontrada ou já não possuía miniatura
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Exposicao
  /expo/{expoId}/painel:
    post:
      tags:
      - exposicao
      summary: Criar um painel em uma exposição
      description: "Cria um painel, e envia um convite para o artista informado."
      operationId: CriarPainel
      parameters:
      - name: expoId
        in: path
        description: ID da exposição onde o painel será criado
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Informações do painel que será criado.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovoPainel'
          application/xml:
            schema:
              $ref: '#/components/schemas/NovoPainel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NovoPainel'
        required: true
      responses:
        "201":
          description: criada com sucesso
          headers:
            location:
              description: onde o novo recurso pode ser encontrado
              style: simple
              explode: false
              schema:
                type: string
                example: http://localhost:8080/api/v1/expo/10/painel/11
        "400":
          description: dados inválidos
        "404":
          description: exposição ou usuário não encontrados
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Exposicao
  /expo/{expoId}/painel/{painelId}:
    get:
      tags:
      - exposicao
      summary: Carregar um painel de uma exposição a partir de seus IDs
      description: "Retorna um único painel, com uma lista de seus elementos."
      operationId: carregarPainelPorId
      parameters:
      - name: expoId
        in: path
        description: ID da exposição cujo o painel a ser carregado pertence
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: painelId
        in: path
        description: ID do painel a ser carregado
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Painel'
            application/xml:
              schema:
                $ref: '#/components/schemas/Painel'
        "400":
          description: um dos ids fornecidos é inválido
        "404":
          description: painel não encontrado
      x-swagger-router-controller: Exposicao
    put:
      tags:
      - exposicao
      summary: Alterar informações de um painel
      description: "Atualiza informações de um painel, assim como seus elementos."
      operationId: atualizarPainel
      parameters:
      - name: expoId
        in: path
        description: ID da exposição cujo painel a ser atualizado pertence
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: painelId
        in: path
        description: ID do painel a ser atualizado
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: |-
          Informações a atualizar no painel.
          Caso a propriedade 'remover' de um elemento seja 'true',
          o elemento com o id informado será removido do painel.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AtualizacaoPainel'
          application/xml:
            schema:
              $ref: '#/components/schemas/AtualizacaoPainel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AtualizacaoPainel'
        required: true
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Painel'
            application/xml:
              schema:
                $ref: '#/components/schemas/Painel'
        "400":
          description: dados inválidos
        "404":
          description: "painel, exposição ou elementos não encontrados"
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Exposicao
    delete:
      tags:
      - exposicao
      summary: Remover um painel de uma exposição
      description: "Remove um único painel de uma exposição, somente se a exposiçã\
        o estiver em modo rascunho"
      operationId: excluirPainel
      parameters:
      - name: expoId
        in: path
        description: ID da exposição cujo o painel a ser removido pertence
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: painelId
        in: path
        description: ID do painel a ser removido
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: operação bem sucedida
        "400":
          description: um dos ids fornecidos é inválido
        "404":
          description: exposição ou painel não encontrados
        "409":
          description: Não é permitido remover esse painel no momento
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Exposicao
  /usuario:
    get:
      tags:
      - usuario
      summary: Buscar usuario
      description: Busca pelo usuario para entrada na plataforma.
      operationId: obterUsuario
      parameters:
      - name: chave
        in: query
        description: A chave do usuario
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Usuario'
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        "404":
          description: Usuario nao encontrado
      x-swagger-router-controller: Usuario
    post:
      tags:
      - usuario
      summary: Criar usuario
      description: Cadastra um novo usuario na plataforma.
      operationId: criarUsuario
      requestBody:
        description: Objeto do usuario criado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CriacaoUsuario'
          application/xml:
            schema:
              $ref: '#/components/schemas/CriacaoUsuario'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CriacaoUsuario'
      responses:
        "200":
          description: operacao bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
            application/xml:
              schema:
                $ref: '#/components/schemas/Usuario'
      x-swagger-router-controller: Usuario
  /usuario/{id}:
    put:
      tags:
      - usuario
      summary: Editar usuario
      description: Altera o nome do usuario
      operationId: atualizarUsuario
      parameters:
      - name: id
        in: path
        description: ID do usuario a ser editado
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          example: 10
      requestBody:
        description: Informações a atualizar no usuário.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AtualizacaoUsuario'
          application/xml:
            schema:
              $ref: '#/components/schemas/AtualizacaoUsuario'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AtualizacaoUsuario'
        required: true
      responses:
        default:
          description: successful operation
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Usuario
    delete:
      tags:
      - usuario
      summary: desconecta o usuario da sessao atual
      description: ""
      operationId: sairUsuario
      parameters:
      - name: id
        in: path
        description: ID do usuario a ser desconectado
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          example: 10
      responses:
        default:
          description: successful operation
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Usuario
  /perfil:
    get:
      tags:
      - perfil
      summary: Buscar perfis cadastrados na plataforma a partir de uma palavra-chave
      description: Busca perfis de usuários cadastrados na plataforma que coincidam
        com a palavra-chave informada.
      operationId: buscarPerfis
      parameters:
      - name: chave
        in: query
        description: A palavra-chave para filtrar os resultados da busca
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: busca bem sucedida encontrou resultados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Perfil'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Perfil'
        "204":
          description: "busca efetuada, porém não encontrou resultados"
        "400":
          description: dados inválidos
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
  /perfil/notificacao:
    get:
      tags:
      - perfil
      summary: Buscar notificações para o usuário ativo
      description: Busca notificações de convites para participação em exposições
      operationId: buscarNotificacoes
      parameters:
      - name: pagina
        in: query
        description: Página atual da busca
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          default: 0
      - name: quantidade
        in: query
        description: Quantidade de registros a serem buscados
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notificacao'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notificacao'
        "204":
          description: nenhuma notificação encontrada
        "400":
          description: requisição inválida
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
    post:
      tags:
      - perfil
      summary: Enviar uma notificação convidando um usuário para uma exposição
      description: Envia um convite para participação em uma exposição
      operationId: enviarNotificacao
      requestBody:
        description: "Dados da exposição, painel e artista que será convidado."
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovaNotificacao'
          application/xml:
            schema:
              $ref: '#/components/schemas/NovaNotificacao'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NovaNotificacao'
      responses:
        "201":
          description: notificação criada com sucesso
          headers:
            location:
              description: onde o novo recurso pode ser encontrado
              style: simple
              explode: false
              schema:
                type: string
                example: http://localhost:8080/api/v1/perfil/notificacao/1001
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConviteExposicao'
            application/xml:
              schema:
                $ref: '#/components/schemas/ConviteExposicao'
        "400":
          description: dados inválidos
        "404":
          description: "exposição, painel ou artista não encontrados"
        "409":
          description: artista já possui convite pendente para esse painel
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
  /perfil/notificacao/{id}:
    get:
      tags:
      - perfil
      summary: Buscar uma notificação a partir do id
      description: Busca uma notificação de convite para participação em uma exposição
      operationId: buscarNotificacaoPorId
      parameters:
      - name: id
        in: path
        description: id da notificação
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 1001
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notificacao'
            application/xml:
              schema:
                $ref: '#/components/schemas/Notificacao'
        "400":
          description: requisição inválida
        "404":
          description: notificação não encontrada
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
    delete:
      tags:
      - perfil
      summary: Cancelar convite para exposição
      description: Cancela um convite para uma exposição
      operationId: removerNotificacao
      parameters:
      - name: id
        in: path
        description: id do convite
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 1001
      responses:
        "200":
          description: operação bem sucedida
        "400":
          description: id do convite inválido
        "404":
          description: convite não encontrado
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
    patch:
      tags:
      - perfil
      summary: Aceitar um convite para exposição a partir de uma notificação
      description: Aceita um convite para participar em um painel de uma exposição
      operationId: aceitarConviteNotificacao
      parameters:
      - name: id
        in: path
        description: id da notificação
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 1001
      responses:
        "200":
          description: operação bem sucedida
        "400":
          description: id da notificação inválido
        "404":
          description: notificação não encontrada
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
  /perfil/contato:
    get:
      tags:
      - perfil
      summary: Buscar canais de contato de um usuário
      description: Busca os canais de contato de um usuario a partir do seu nome
      operationId: buscarContatos
      parameters:
      - name: pagina
        in: query
        description: Página atual da busca
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          default: 0
      - name: quantidade
        in: query
        description: Quantidade de registros a serem buscados
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contato'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contato'
        "204":
          description: nenhuma notificação encontrada
        "400":
          description: requisição inválida
      x-swagger-router-controller: Perfil
    post:
      tags:
      - perfil
      summary: Adicionar canal de contato ao perfil do usuario
      description: Adiciona um canal de contato ao perfil da conta da sessão atual
      operationId: adicionarContato
      requestBody:
        description: Dados de contato a serem cadastrados.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovoContato'
          application/xml:
            schema:
              $ref: '#/components/schemas/NovoContato'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NovoContato'
      responses:
        "201":
          description: contato criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201_1'
        "400":
          description: dados inválidos
        "404":
          description: "exposição, painel ou artista não encontrados"
        "409":
          description: artista já possui convite pendente para esse painel
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
  /perfil/contato/{id}:
    get:
      tags:
      - perfil
      summary: Buscar um canal de contato a partir do id
      description: Busca um canal de contato de um artista
      operationId: buscarContatoPorId
      parameters:
      - name: id
        in: path
        description: id da notificação
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 1001
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contato'
            application/xml:
              schema:
                $ref: '#/components/schemas/Contato'
        "400":
          description: requisição inválida
        "404":
          description: notificação não encontrada
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
    put:
      tags:
      - perfil
      summary: Atualizar canal de contato
      description: Atualiza um canal de contato
      operationId: atualizarContato
      parameters:
      - name: id
        in: path
        description: id do contato
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 1001
      requestBody:
        description: Dados para atualização do canal de contato
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/AtualizacaoContato'
      responses:
        "200":
          description: operação bem sucedida
        "400":
          description: id do contato inválido
        "404":
          description: contato não encontrado
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
    delete:
      tags:
      - perfil
      summary: Remover canal de contato
      description: Remove um canal de contato
      operationId: removerContato
      parameters:
      - name: id
        in: path
        description: id do contato
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 1001
      responses:
        "200":
          description: operação bem sucedida
        "400":
          description: id do contato inválido
        "404":
          description: contato não encontrado
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
  /perfil/acervo/obra:
    get:
      tags:
      - perfil
      summary: Listar obras no acervo do usuário
      description: Lista as obras no acervo do usuário.
      operationId: carregarObras
      parameters:
      - name: pagina
        in: query
        description: Página atual da busca
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          default: 0
      - name: quantidade
        in: query
        description: Quantidade de registros a serem buscados
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          default: 10
      - name: tipo
        in: query
        description: Tipo de filtro para aplicar na busca
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: todos
          enum:
          - todos
          - imagem
          - audio
          - video
      - name: ordenacao
        in: query
        description: Tipo de ordenacao para aplicar na busca
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: recentes
          enum:
          - recentes
          - antigas
          - crescente
          - decrescente
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Obra'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Obra'
        "400":
          description: dados inválidos
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
    post:
      tags:
      - perfil
      summary: Carregar obra no acervo do usuário
      description: Adiciona uma obra ao acervo do usuário.
      operationId: adicionarObra
      requestBody:
        description: Dados da obra a ser carregada no acervo.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovaObra'
          application/xml:
            schema:
              $ref: '#/components/schemas/NovaObra'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NovaObra'
      responses:
        "201":
          description: obra criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Obra'
            application/xml:
              schema:
                $ref: '#/components/schemas/Obra'
        "400":
          description: dados inválidos
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
  /perfil/acervo/obra/{id}:
    get:
      tags:
      - perfil
      summary: Carregar obra do acervo do usuário
      description: Carrega uma obra do acervo do usuário.
      operationId: carregarObra
      parameters:
      - name: id
        in: path
        description: ID da obra a ser carregada
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 10
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Obra'
            application/xml:
              schema:
                $ref: '#/components/schemas/Obra'
        "400":
          description: dados inválidos
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
    put:
      tags:
      - perfil
      summary: Editar obra do acervo do usuário
      description: Edita uma obra do acervo do usuário.
      operationId: atualizarObra
      parameters:
      - name: id
        in: path
        description: ID da obra a ser atualizada
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 10
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AtualizacaoObra'
          application/xml:
            schema:
              $ref: '#/components/schemas/AtualizacaoObra'
      responses:
        "200":
          description: operação bem sucedida
        "400":
          description: ID da obra inválido
        "404":
          description: não foi possível encontrar a obra
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
    delete:
      tags:
      - perfil
      summary: Remover uma obra do acervo do usuário
      description: "Remove uma obra do acervo do usuário. Também remove o arquivo\
        \ da obra do servidor, se houver."
      operationId: removerObra
      parameters:
      - name: id
        in: path
        description: ID da obra a ser removida
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          default: 10
      responses:
        "200":
          description: operação bem sucedida
        "400":
          description: ID da obra inválido
        "404":
          description: não foi possível encontrar a obra
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
    patch:
      tags:
      - perfil
      summary: Adicionar um arquivo a uma obra
      description: Carrega um novo arquivo para uma obra
      operationId: adicionarArquivoObra
      parameters:
      - name: id
        in: path
        description: ID da obra a qual o arquivo pertencerá
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: |-
          Arquivo que será carregado na obra.
          Deve ser de um formato suportado pelo tipo da obra
        content:
          image/png:
            schema:
              type: string
              format: binary
          image/jpeg:
            schema:
              type: string
              format: binary
          image/*:
            schema:
              type: string
              format: binary
          audio/mp3:
            schema:
              type: string
              format: binary
          audio/wav:
            schema:
              type: string
              format: binary
          audio/*:
            schema:
              type: string
              format: binary
        required: true
      responses:
        "200":
          description: operacao bem sucedida
        "400":
          description: id fornecido é inválido
        "404":
          description: obra não encontrada
        "413":
          description: conteúdo muito grande
        "415":
          description: tipo de mídia não suportado
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
  /perfil/painel:
    get:
      tags:
      - perfil
      summary: Carregar painéis mantidos pelo usuário
      description: Carrega os painéis de exposições que o usuário aceitou participar.
      operationId: carregarMeusPaineis
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResumoMeuPainel'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResumoMeuPainel'
        "204":
          description: nenhuma exposição para mostrar
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
  /perfil/expo:
    get:
      tags:
      - perfil
      summary: Carregar exposições organizadas pelo usuário
      description: Carrega as exposições que o usuário organizou.
      operationId: carregarMinhasExposicoes
      responses:
        "200":
          description: operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResumoExposicao'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResumoExposicao'
        "204":
          description: nenhuma exposição para mostrar
      security:
      - underexpoAuth: []
      x-swagger-router-controller: Perfil
components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        nome:
          type: string
          example: artistaA
      example:
        nome: artistaA
        id: 10
      xml:
        name: Usuario
    CriacaoUsuario:
      type: object
      properties:
        chave:
          type: string
          example: "115626206216540"
        nome:
          type: string
          example: artistaA
      xml:
        name: Usuario
    AtualizacaoUsuario:
      type: object
      properties:
        nome:
          type: string
          example: artistaA
    Exposicao:
      required:
      - nome
      - organizador
      type: object
      properties:
        nome:
          type: string
          example: Exposição A
        descricao:
          type: string
          example: Lorem ipsum dolor sit amet.
        organizador:
          type: string
          example: artistaB
        paineis:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/ResumoPainel'
        convites:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/ConviteExposicao'
      example:
        convites:
        - artista: artistaA
          expoId: 10
          id: 1001
        - artista: artistaA
          expoId: 10
          id: 1001
        paineis:
        - urlMiniatura: https://source.unsplash.com/random?wallpapers
          nome: Painel A
          id: 10
          autor: artistaB
        - urlMiniatura: https://source.unsplash.com/random?wallpapers
          nome: Painel A
          id: 10
          autor: artistaB
        nome: Exposição A
        descricao: Lorem ipsum dolor sit amet.
        organizador: artistaB
      xml:
        name: exposicao
    ResumoExposicao:
      required:
      - nome
      - organizador
      - urlMiniatura
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        nome:
          type: string
          example: Exposição A
        descricao:
          type: string
          example: lorem ipsum
        urlMiniatura:
          type: string
          example: https://source.unsplash.com/random?wallpapers
        organizador:
          type: string
          example: artistaB
      example:
        urlMiniatura: https://source.unsplash.com/random?wallpapers
        nome: Exposição A
        id: 10
        descricao: lorem ipsum
        organizador: artistaB
      xml:
        name: exposicoes
    NovaExposicao:
      required:
      - nome
      type: object
      properties:
        nome:
          type: string
          example: Exposição A
        descricao:
          type: string
          example: Lorem ipsum dolor sit amet.
      xml:
        name: exposicao
    AtualizacaoExposicao:
      type: object
      properties:
        nome:
          type: string
          example: Exposição A
        descricao:
          type: string
          example: Lorem ipsum dolor sit amet.
        paineis:
          type: array
          items:
            $ref: '#/components/schemas/AtualizacaoExposicao_paineis'
      xml:
        name: exposicao
    NotificacaoExposicao:
      required:
      - nome
      - organizador
      - painelId
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        painelId:
          type: integer
          format: int64
          example: 11
        nome:
          type: string
          example: Exposição A
        organizador:
          type: string
          example: artistaB
      example:
        painelId: 11
        nome: Exposição A
        id: 10
        organizador: artistaB
      xml:
        name: exposicoes
    Painel:
      required:
      - autor
      - nome
      type: object
      properties:
        nome:
          type: string
          example: Painel A
        autor:
          type: string
          example: artistaB
        elementos:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Elemento'
      example:
        elementos:
        - tipo: T
          conteudo: Lorem ipsum dolor sit amet.
          titulo: Título do Elemento
          id: 10
        - tipo: T
          conteudo: Lorem ipsum dolor sit amet.
          titulo: Título do Elemento
          id: 10
        nome: Painel A
        autor: artistaB
      xml:
        name: painel
    ResumoPainel:
      required:
      - autor
      - nome
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        nome:
          type: string
          example: Painel A
        urlMiniatura:
          type: string
          example: https://source.unsplash.com/random?wallpapers
        autor:
          type: string
          example: artistaB
      example:
        urlMiniatura: https://source.unsplash.com/random?wallpapers
        nome: Painel A
        id: 10
        autor: artistaB
      xml:
        name: painel
    ResumoMeuPainel:
      required:
      - autor
      - id
      - idExposicao
      - nome
      - nomeExposicao
      - organizador
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        nome:
          type: string
          example: Painel A
        urlMiniatura:
          type: string
          example: https://source.unsplash.com/random?wallpapers
        autor:
          type: string
          example: artistaB
        exposicao:
          $ref: '#/components/schemas/ResumoExposicao'
      example:
        urlMiniatura: https://source.unsplash.com/random?wallpapers
        nome: Painel A
        id: 10
        autor: artistaB
        exposicao:
          urlMiniatura: https://source.unsplash.com/random?wallpapers
          nome: Exposição A
          id: 10
          descricao: lorem ipsum
          organizador: artistaB
      xml:
        name: painel
    NovoPainel:
      required:
      - autorId
      type: object
      properties:
        autorId:
          type: integer
          format: int64
          example: 1000
      xml:
        name: painel
    AtualizacaoPainel:
      required:
      - nome
      type: object
      properties:
        nome:
          type: string
          example: Painel A
        elementos:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/AtualizacaoElemento'
      xml:
        name: painel
    Elemento:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        titulo:
          type: string
          description: Texto opcional que ficará em destaque logo antes do conteúdo
            do elemento
          example: Título do Elemento
        tipo:
          type: string
          description: tipo de elemento
          enum:
          - T
          - I
          - A
          - V
        conteudo:
          type: string
          description: |-
            Dendendo do tipo do elemento pode ser texto plano, url para uma imagem,
            url para um arquivo de áudio ou url para um vídeo.
          example: Lorem ipsum dolor sit amet.
      example:
        tipo: T
        conteudo: Lorem ipsum dolor sit amet.
        titulo: Título do Elemento
        id: 10
      xml:
        name: elemento
    AtualizacaoElemento:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        remover:
          type: boolean
          example: false
        indice:
          type: integer
          description: |-
            posição do elemento no painel. Se outro elemento já possui o mesmo índice,
            ele irá assumir a antiga posição do elemento atualizado.
          format: int32
          example: 1
        titulo:
          type: string
          description: Texto opcional que ficará em destaque logo antes do conteúdo
            do elemento
          example: Título do Elemento
        tipo:
          type: string
          description: tipo de elemento
          enum:
          - T
          - I
          - A
          - V
        conteudo:
          type: string
          description: "Conteúdo de texto plano, caso o elemento seja do tipo texto."
          example: Lorem ipsum dolor sit amet.
        obraId:
          type: integer
          description: ID da obra que será apresentada no elemento
          format: int64
          example: 11
      xml:
        name: elemento
    Notificacao:
      required:
      - expo
      - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1001
        expo:
          $ref: '#/components/schemas/NotificacaoExposicao'
      example:
        id: 1001
        expo:
          painelId: 11
          nome: Exposição A
          id: 10
          organizador: artistaB
      xml:
        name: notificacao
    ConviteExposicao:
      required:
      - artista
      - expoId
      - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1001
        expoId:
          type: integer
          format: int64
          example: 10
        artista:
          type: string
          example: artistaA
      example:
        artista: artistaA
        expoId: 10
        id: 1001
      xml:
        name: notificacao
    NovaNotificacao:
      required:
      - autorId
      - expoId
      type: object
      properties:
        expoId:
          type: integer
          format: int64
          example: 10
        autorId:
          type: integer
          format: int64
          example: 1000
      xml:
        name: notificacao
    Contato:
      required:
      - canal
      - id
      - link
      - nome
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10001
        canal:
          type: string
          example: Instagram
        nome:
          type: string
          example: '@meu.instagram'
        link:
          type: string
          example: http://www.instagram.com/meu.instagram
      example:
        link: http://www.instagram.com/meu.instagram
        nome: '@meu.instagram'
        id: 10001
        canal: Instagram
      xml:
        name: contato
    AtualizacaoContato:
      type: object
      properties:
        canal:
          type: string
          example: Instagram
        nome:
          type: string
          example: '@meu.instagram'
        link:
          type: string
          example: http://www.instagram.com/meu.instagram
      xml:
        name: contato
    NovoContato:
      required:
      - canal
      - link
      - nome
      type: object
      properties:
        canal:
          type: string
          example: Instagram
        nome:
          type: string
          example: '@meu.instagram'
        link:
          type: string
          example: http://www.instagram.com/meu.instagram
      xml:
        name: contato
    Obra:
      required:
      - dataCarregamento
      - id
      - nome
      - tipo
      - url
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        nome:
          type: string
          example: Imagem A
        tipo:
          type: string
          description: tipo de elemento
          enum:
          - imagem
          - audio
          - video
        dataCarregamento:
          type: string
          format: date
        url:
          type: string
          example: https://source.unsplash.com/random?wallpapers
      example:
        tipo: imagem
        nome: Imagem A
        id: 10
        dataCarregamento: 2000-01-23
        url: https://source.unsplash.com/random?wallpapers
      xml:
        name: obra
    NovaObra:
      required:
      - nome
      - tipo
      type: object
      properties:
        nome:
          type: string
          example: Imagem A
        tipo:
          type: string
          description: tipo de elemento
          enum:
          - imagem
          - audio
          - video
      xml:
        name: obra
    AtualizacaoObra:
      type: object
      properties:
        nome:
          type: string
          example: Imagem A
      xml:
        name: obra
    NovaDenuncia:
      required:
      - descricao
      type: object
      properties:
        descricao:
          type: string
          example: Lorem ipsum dolor sit amet.
      xml:
        name: denuncia
    Perfil:
      required:
      - id
      - nome
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10000
        nome:
          type: string
          example: artistaA
      example:
        nome: artistaA
      xml:
        name: perfil
    inline_response_201:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
          example: 10
      example:
        id: 10
    inline_response_201_1:
      type: object
      properties:
        id:
          type: integer
          example: 10001
      example:
        id: 10001
    AtualizacaoExposicao_paineis:
      required:
      - id
      - indice
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        indice:
          type: integer
          format: int32
          example: 1
  securitySchemes:
    underexpoAuth:
      type: apiKey
      name: x-user-key
      in: header
